# Build Stage for Spring boot application image
FROM maven:3.8.1-jdk-11

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline
RUN mvn spring-javaformat:help

COPY . ./
RUN mvn package

ARG JAR_FILE=./target/*.jar
COPY ${JAR_FILE} ./swplanets.jar
CMD ["java", "-jar", "/app/swplanets.jar"]

