# Build Stage for Spring boot application image
FROM maven:3.8.1-jdk-11 as build

WORKDIR /app

COPY pom.xml ./
RUN mvn dependency:go-offline
RUN mvn spring-javaformat:help

COPY . ./
RUN mvn spring-javaformat:apply
RUN mvn package

FROM openjdk:11-jre-slim-buster
EXPOSE 8080
WORKDIR /app

ARG JAR_FILE=/app/target/*.jar

COPY --from=build ${JAR_FILE} ./swplanets.jar
CMD ["java", "-jar", "/app/swplanets.jar"]
