version: '3.7'

services:
  app:
    build:
      context: .
    volumes:
      - m2:/root/.m2
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: .docker/mongo
    ports:
      - '27117:27017'
    networks:
      - app-network
    volumes:
      - ./.docker/mongo/data:/data/db

volumes:
  m2: {}

networks:
  app-network:
    driver: bridge
