version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: swplanets_app
    volumes:
      - m2:/root/.m2
    networks:
      - app-network
    depends_on:
      - db

  db:
    build: .docker/mongo
    networks:
      - app-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
      - MONGO_INITDB_DATABASE=swplanets
    volumes:
      - ./.docker/mongo/data:/data/db

volumes:
  m2: {}

networks:
  app-network:
    driver: bridge
