# Build Stage for Spring boot application image
FROM maven:3.8.1-jdk-11

WORKDIR /app

COPY pom.xml /app
RUN mvn dependency:go-offline
RUN mvn spring-javaformat:help

COPY . /app/
RUN mvn package

COPY /app/target/*.jar /app/swplanets.jar
CMD ["java", "-jar", "/app/swplanets.jar"]

